### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [a-pavlov/jed2k#75]
Is this okay with you?

Ref: https://forum.f-droid.org/t/emule-ed2k-clients/7122/9

Ref: https://f-droid.org/en/docs/Inclusion_Policy/

This recipe **metadata/org.dkf.jmule.yml** builds fine:
```
AntiFeatures:
  - NonFreeNet
  - Tracking
Categories:
  - Internet
License: Apache-2.0
SourceCode: https://github.com/a-pavlov/jed2k
IssueTracker: https://github.com/a-pavlov/jed2k/issues

AutoName: Mule on Android

RepoType: git
Repo: https://github.com/a-pavlov/jed2k

Builds:
  - versionName: '33'
    versionCode: 33
    commit: 3.3
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y openjdk-11-jdk-headless
      - update-alternatives --auto java
    gradle:
      - yes
    output: android/jdonkey/build/outputs/apk/basic/release/jed2k-android-release-$$VERSION$$-b$$VERCODE$$-basic.apk
    prebuild: sed -i -e 's/0001 + //' android/jdonkey/build.gradle

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '33'
CurrentVersionCode: 33
```

If it's okay, some sort of Fastlane _(just folder)_ structure would be nice to setup, eg. https://gitlab.com/-/snippets/1895688 to have pics, icon, changelogs and description hosted here.

/LE: 40c4b401d39d02aaaa16f7975780d5e35f6d97b2 yielded versionName/Code as 33 & 34 in the output APK, rather odd, retrying with d47b928268de74c96c75d9570c8625d214872ae7 since I know that 34/34 build fine earlier.

/LE2: oh that's why https://github.com/a-pavlov/jed2k/blob/e284f4faca181d2b617a4805ebefe2bbd23b4969/android/jdonkey/build.gradle#L153 pfft

/LE3: add AF since it depends on `server-met.emulefuture.de/download.php?file=nodes.dat` (why is this NOT httpS???) and `raw.githubusercontent.com/a-pavlov/jed2k/config/config.json`, [VT report](https://www.virustotal.com/gui/file/3ea3925c2f362788e549fb3b4c04c03dd9f5b48e6b54e3c6a6e707cc38f844a8/details)

/LE4: also connections to `clients1.google.com` brrr so there's another AF there :(
